// Copyright 13-Apr-2020 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

//  Structures template.
//
//  Parts
//
//  Teplate has the following parts:
//    /*·
//    [-]identifier
//    parameters (used in New)
//    -
//    variables
//    ---
//    functions
//    */
//    code (Generated by gotpl)
//    //===
//  .
//
//  Identifier
//
//  Only has one element.
//    name. ('-' indicate that the structure is private)
//    Special names are:
//      T, t, bool, int, int32, int64, float32, float64 & string
//  Example:
//    # Personal data
//    #   Only or user registred
//    T
//  .
//
//  Parameters
//
//  (Optional) Struct fields which appear in constructor. Each entry is in one
//  line.
//    [+-]name type ('+': with setter, '-': Without setter or getter)
//    Special types are:
//      T, t, xxx.T, bool, int, int32, int64, float32, float64 & string
//  Example:
//    # Ammount of personal account
//    +ammount float64
//  .
//
//  Variables
//
//  (Optional) Struct fields which not appear in constructor. Each entry is in
//  one line.
//
//  'value' is optional.
//    [+-]name type [value] ('+': with setter, '-': Without setter or getter)
//    Special types are:
//      T, t, xxx.T, bool, int, int32, int64, float32, float64 & string
//  Example:
//    # Profits ratio
//    -profits float64 total / inversion
//  .
//
//  Functions
//
//  (Optional) Each function has it own syntax. Several templates can be
//  in a same line. Spaces are optionals. See package 'funcs'.
//    tp1 ·· tp2 ·· ... ·· tpn
//    tpn1 ·· tpn2 ...
//  Example
//    toJs··fromJs··map·string
package structs
